# =========== Dependencies ===========

# Tmux Plugin Manager (tpm)
#   Install here: https://github.com/tmux-plugins/tpm

# spotify-cli-linux
#   Install by running: pip install spotify-cli-linux

# =========== General Settings ===========

# Rebind leader to Control + s
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Bind r to reload ~/.tmux.conf
#bind r source-file "~/.tmux.conf"; display-message "Reloaded .tmux.conf"

# Remove delay on escape character
set -s escape-time 0

# =========== Panes Settings ===========

unbind '"'
unbind %
bind \ split-window -h
bind - split-window -v

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

set-option -g pane-active-border-style "bg=default"
set-option -ag pane-active-border-style "fg=colour78"

# =========== Plugins ===========

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'robhurring/tmux-spotify'

# =========== Plugin Settings ===========

# tmux-spotify
set -g @spotify_playing_icon "▶︎ "
set -g @spotify_paused_icon "❚❚"

# tmux-battery
set -g @batt_remain_short true

# tmux-online-status
#set -g @online_icon "Online"
#set -g @offline_icon "Offline"

# =========== Status Bar ===========

set -g status-interval 1
set -g status-right-length 100
set -g status-right "%a %y-%m-%d | %H:%M "
set -g status-bg colour78

# =========== Run tmux plugin manager ===========

run -b '~/.tmux/plugins/tpm/tpm'

