# =========== Dependencies ===========

# Tmux Plugin Manager (tpm)
# Install here: https://github.com/tmux-plugins/tpm

# =========== General Settings ===========

# Rebind leader to Control + s
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Bind r to reload ~/.tmux.conf
unbind r
bind r source-file ~/.tmux.conf; display-message "Reloaded .tmux.conf"

# Remove delay on escape character
set -s escape-time 0

# Don't exit from tmux when closing a session
set -g detach-on-destroy off

# Allow us to scroll with mouse in copy mode
# and select via mouse
set -g mouse on

# =========== Panes Settings ===========

unbind '"'
unbind %
bind \\ split-window -h
bind - split-window -v

setw -g mode-keys vi
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind H resize-pane -L 15
bind L resize-pane -R 15
bind K resize-pane -U 15
bind J resize-pane -D 15

# =========== Copy/Paste with vim keys ===========

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# =========== Plugins ===========

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'

# =========== Status Bar Settings ===========

set -g @dracula-show-powerline true
set -g @dracula-fix-location "Seattle"
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g -g status-position top

# =========== Run tmux plugin manager ===========
run -b '~/.tmux/plugins/tpm/tpm'
