#!/usr/bin/env sh
#
# github repo:
# https://github.com/koekeishiya/yabai
#
# How I found out about this:
# https://cbrgm.net/post/2021-05-5-setup-macos/
#
# A good video on the subject:
# https://www.youtube.com/watch?v=k94qImbFKWE

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child

# Mouse support
yabai -m config mouse_modifier  alt
# left click + drag = move
yabai -m config mouse_action1   move
# right click + drag = resize
yabai -m config mouse_action2   resize
# when a window is dragged to center of another window, swap them
yabai -m mouse_drop_action      swap

# bsp, stack, or float
yabai -m config layout bsp

# padding
yabai -m config top_padding    12
yabai -m config bottom_padding 12
yabai -m config left_padding   12
yabai -m config right_padding  12
yabai -m config window_gap     12

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off

echo "yabai configuration loaded.."
